---
version: "3"

services:
  firefly:
    image: fireflyiii/core:version-6.0.16
    container_name: firefly
    restart: unless-stopped
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ~/selfhosted/data/firefly/upload:/var/www/html/storage/upload
    networks:
      - cdp # upstreams 8080
      - firefly
    depends_on:
      - firefly-db

  firefly-importer:
    image: fireflyiii/data-importer:version-1.3.1
    container_name: firefly-importer
    restart: unless-stopped
    labels:
      caddy: ${IMPORTER_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.import: fa_authentik /*
    env_file:
      - .env
      - .importer.env
    environment:
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://${DOMAIN}
    networks:
      - cdp # upstreams 8080
      - firefly

  firefly-db:
    image: mariadb:10.6
    container_name: firefly-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ~/selfhosted/data/firefly/db:/var/lib/mysql
    networks:
      - firefly

  firefly-cron:
    image: alpine
    container_name: firefly-cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - firefly
    networks:
      - firefly

  ###
  # must have a pre-set up Plaid account, see https://github.com/dvankley/firefly-plaid-connector-2#configuration
  ###
  firefly-plaid:
    image: ghcr.io/dvankley/firefly-plaid-connector-2:v1.0.5
    container_name: firefly-plaid
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_CONFIG_LOCATION=/opt/fpc-config/application.yml
      - FIREFLYPLAIDCONNECTOR2_POLLED_CURSORFILEDIRECTORYPATH=/opt/fpc-cursors
    volumes:
      - ./application.yml:/opt/fpc-config/application.yml:ro
      - ~/selfhosted/data/firefly/plaid:/opt/fpc-cursors
    networks:
      - firefly

  plaid-quickstart-fe:
    build:
      context: ./quickstart
      dockerfile: ./frontend/Dockerfile
    container_name: plaid-quickstart-fe
    restart: unless-stopped
    labels:
      caddy: ${PLAID_QS_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.import: fa_authentik /*
    env_file:
      - .env
    environment:
      - REACT_APP_API_HOST=http://plaid-quickstart-be:8000
    networks:
      - cdp # upstreams 3000
      - firefly

  plaid-quickstart-be:
    build:
      context: ./quickstart
      dockerfile: ./node/Dockerfile
    container_name: plaid-quickstart-be
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - firefly

networks:
  cdp:
    external: true
  firefly: