---
version: "3.9"

services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: ${HOSTNAME}
    user: "0:0"
    restart: "unless-stopped"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --insecure
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=${SERVER_USERNAME}
      - --server-password=${SERVER_PASSWORD}
    env_file:
      - .env
    volumes:
      - /mnt/kopia:/tmp:shared
      - ~/selfhosted/data/kopia/config:/app/config
      - ~/selfhosted/data/kopia/cache:/app/cache
      - ~/selfhosted/data/kopia/logs:/app/logs
      - ~/selfhosted:/data:ro
    networks:
      - caddy

networks:
  caddy:
    external: true
