---
version: "3.9"

services:
  kroac:
    image: halverneus/static-file-server:v1.8.6
    container_name: kroac
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
      - ./site:/web
    env_file:
      - .env
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true
