version: "3.9"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy:v2.5.0
    container_name: caddy
    labels:
      caddy.acme_dns: "cloudflare {env.CF_API_TOKEN}"
      caddy.email: "{env.EMAIL}"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    env_file:
      - .env
    networks:
      - caddy
      - cloudflared
    volumes:
      # for caddy-docker-proxy to work
      - /var/run/docker.sock:/var/run/docker.sock
      # for caddy itself
      - ~/data/caddy/data:/data
      - ~/data/caddy/config:/config
    restart: unless-stopped

networks:
  caddy:
    external: true
  cloudflared:
    external: true