---
version: "3.9"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy:v2.6.2
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/selfhosted/data/caddy/data:/data
      - ~/selfhosted/data/caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy

networks:
  caddy:
    external: true
